### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by brysgo**
@tylergannon - can you take a look at this and tell me what you think?

### CODE REVIEW

**Comment by tylergannon** [comment]
What's the rationale here?  Is JWT not doing what it's supposed to do?

**Comment by tylergannon** [comment]
What's wrong with JWT, and why are you not using something like https://github.com/lanetix/react-jwt-store

**Comment by tylergannon** [comment]
The use of UserID seems like a pretty insecure auth token, though of course for the moment it will suffice to keep development moving forward.

**Comment by brysgo** [comment]
I fail to see how jwt is more secure then cookie session store. Maybe I missed something.

**Comment by brysgo** [comment]
*Closing PR was an accident

**Comment by tylergannon** [comment]
Touché.  There are some extra gains with JWT, like authorization listing on the token for the client to use, not to mention the fact that it's coming up as a web standard and might be nice to learn to support it.

But I think I agree, as long as your app is secure than your use of session store is secure as well.

**Comment by tylergannon** [comment]
But what I would most like to know, is, was it working when you replaced it, or was something broken?

**Comment by brysgo** [comment]
@tylergannon - It was working, I just hadn't implemented storing the token.

**Pull request merged**
